### PR TITLE
add new script and css to fix instagram footer

### PR DESCRIPTION
**Pull request by mhisle22**
Redo of old instagram feed in footer. Now uses a workaround script instead of Instagram's actual API, which is far too restrictive. Currently 9 elements are pulled (max of 20) and formatted into a grid using some CSS magic. All images are adjusted to fit into 100x100 squares while still fitting in the grid correctly, along with allowing zoom on mouse hover. Let me know if you like the design.

### CODE REVIEW

**Comment by raney24** [comment]
@mhisle22 got it. Thanks for looking into #1 and fixing #2. I think a better solution to #1 would be to make it scale less. Maybe something like 1.5x-2x would kind of "hide" the aspect ratio issue

**Comment by raney24** [comment]
@mhisle22 Checking to see if you saw my comment above

**Comment by mhisle22** [comment]
@raney24 images now scale to 2 instead of 3. Also, I found that some images went back to cutting off, so I redid the way columns were created and it now works correctly. On screen-lg sizes it now forms 2 columns and chops off the 8th element, looks almost the same but let me know if you still like the design on that screen size.

**Comment by raney24** [comment]
@mhisle22 this looks great. No bugs on my end and I like the design.

Sorry for the late request, but how hard would it be to make the images link to the respective post on IG?

**Comment by mhisle22** [comment]
@raney24 I do not believe that it would be possible to have direct links to the posts using the method that I found- I think that would require the use of the actual instagram API or possibly another library. However, I could pretty quickly add links to the Ainc's general instagram page to the images if you want.

I don't know if I showed you it before, but the method I used is mostly based off of this: https://rudrastyh.com/instagram/get-photos-and-profile-info-pure-javascript.html

**Pull request merged**
