### PR TITLE
Corevalues merge

### PR DESCRIPTION
**Pull request by skyebrownh**
The corevalues branch has been completed and is ready to be reviewed, merged into master, and deleted.

### CODE REVIEW

**Comment by raney24** [comment]
@skyebrownh Can you make this more responsive? It looks like the buttons and CV image overlap on mobile and tablet.

**Comment by skyebrownh** [comment]
> @skyebrownh Can you make this more responsive? It looks like the buttons and CV image overlap on mobile and tablet.

done.

**Comment by skyebrownh** [comment]
@raney24 don't forget to delete this branch

**Comment by raney24** [comment]
@skyebrownh Thanks for the reminder!

**Pull request merged**
