### PR TITLE
Blog bugs

### PR DESCRIPTION
**Pull request by skyebrownh**
Blog bugs checklist has been completed and is ready to be merged into master.

### CODE REVIEW

**Comment by raney24** [comment]
@skyebrownh This looks good. Two things:
 - One thing: Can you add the description field into the admin/config.yml blog object? Also, make it `required: false`

**Comment by skyebrownh** [comment]
> @skyebrownh This looks good. Two things:
> 
> * One thing: Can you add the description field into the admin/config.yml blog object? Also, make it `required: false`

@raney24 I would strongly suggest making this field required so we don't run into the same bugs I just fixed. If not, images and links might cause the preview and/or layout of the blog page to break.

**Comment by raney24** [comment]
@skyebrownh Okay, good point. You can leave it as required!

**Comment by skyebrownh** [comment]
@raney24 also, should I be merging with the netlify-cms branch first to test if its working in the CMS with the `branch` variable in admin/config.yml being `netlify-cms` and then requesting for netlify-cms to be merged into master? I'm still a little confused on that workflow.

**Comment by raney24** [comment]
@skyebrownh Go ahead and merge with master. I think for big changes (like adding a collection) we need to stage it on netlify-cms. 

I am going to try and come up with an infrastructure / protocol for how we make changes before the fall team arrives.

**Comment by skyebrownh** [comment]
@raney24 a required description field has been added to the CMS. I also made sure all the blog posts had descriptions so there wouldn't be any conflicts.

**Comment by skyebrownh** [comment]
@raney24 this branch should be good to merge.

**Pull request merged**
